export enum AgentType {
  LEAD_GENERATION = 'LEAD_GENERATION',
  LINKEDIN_OUTREACH = 'LINKEDIN_OUTREACH',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  ADVERTISING = 'ADVERTISING',
  APPOINTMENT_SETTER = 'APPOINTMENT_SETTER',
  VOICE_INBOUND = 'VOICE_INBOUND',
  VOICE_OUTBOUND = 'VOICE_OUTBOUND',
  VOICE_CLOSER = 'VOICE_CLOSER',
  CLIENT_SERVICES = 'CLIENT_SERVICES',
}

export enum AgentStatus {
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ERROR = 'ERROR',
}

export const PLANS: Record<string, { agents: AgentType[] }> = {
  STARTER: {
    agents: [AgentType.LEAD_GENERATION, AgentType.SOCIAL_MEDIA, AgentType.VOICE_INBOUND],
  },
  GROWTH: {
    agents: [AgentType.LEAD_GENERATION, AgentType.LINKEDIN_OUTREACH, AgentType.SOCIAL_MEDIA, AgentType.ADVERTISING, AgentType.APPOINTMENT_SETTER, AgentType.VOICE_INBOUND, AgentType.VOICE_OUTBOUND],
  },
  AGENCY: {
    agents: [AgentType.LEAD_GENERATION, AgentType.LINKEDIN_OUTREACH, AgentType.SOCIAL_MEDIA, AgentType.ADVERTISING, AgentType.APPOINTMENT_SETTER, AgentType.VOICE_INBOUND, AgentType.VOICE_OUTBOUND, AgentType.VOICE_CLOSER, AgentType.CLIENT_SERVICES],
  },
}
